# Generated by Django 4.2.5 on 2023-09-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_decription',
            new_name='course_description',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='course_module_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='video_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pro_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscription_type',
            field=models.CharField(choices=[('F', 'FREE'), ('M', 'MONTHLY'), ('Y', 'YEARLY')], default='FREE', max_length=100),
        ),
    ]
