# Generated by Django 4.2.5 on 2023-09-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_rename_course_decription_course_course_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_description',
            new_name='course_decription',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='course_module_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='coursemodule',
            name='video_url',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pro_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscription_type',
            field=models.CharField(choices=[('F', 'FREE'), ('M', 'Monthly'), ('Y', 'Yearly')], default='FREE', max_length=100),
        ),
    ]
