# Generated by Django 4.2.5 on 2023-09-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rename_course_description_course_course_decription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodule',
            name='video_url',
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='video',
            field=models.FileField(blank=True, upload_to='video/%y'),
        ),
    ]
