# Generated by Django 4.2.5 on 2023-09-19 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_remove_coursemodule_video_url_coursemodule_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=20)),
                ('test_video', models.FileField(upload_to='test_video')),
            ],
        ),
    ]
