# Generated by Django 4.2.5 on 2023-09-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test',
            new_name='Test_video',
        ),
    ]
