# Generated by Django 4.2.5 on 2023-09-19 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_rename_test_test_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_video',
        ),
    ]
